
services:
  mariadb:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "--password=root"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mariadb

  vaccine:
    build:
      context: ./services/vaccine
    container_name: vaccine-service
    ports:
      - "4005:4005"
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: pet
    depends_on:
      mariadb:
        condition: service_healthy
  auth:
    build:
      context: ./services/auth
    container_name: auth-service
    ports:
      - "4001:4001"
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: pet
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  mariadb-data:
